'use client';

import { useEffect, useState } from 'react';
import { Aperture, Camera, CheckCircle2, ChevronDown, Download, Focus, Gauge, Home as HomeIcon, Menu, Moon, Mountain, PawPrint, Sparkles, Sun, WifiOff, X, Zap } from 'lucide-react';

const scenarios = [
  { id:'dia', icon:Sun, title:'Fotos de dia', label:'Dia', color:'sun', lens:'18–35 mm', mode:'Av', aperture:'f/8', shutter:'1/250 s ou mais', iso:'100–200', focus:'One Shot', tip:'Comece com o sol de lado ou atrás de você. Para paisagens, use 18 mm; para pessoas, aproxime para 35–55 mm.', steps:['Gire o seletor para Av.','Escolha f/8 e ISO 100.','Aperte o disparador até a metade para focar.','Confira se a velocidade ficou em 1/125 s ou mais.'], avoid:'Sol forte direto no rosto cria olhos semicerrados e sombras duras.' },
  { id:'noite', icon:Moon, title:'Fotos à noite', label:'Noite', color:'night', lens:'18–35 mm', mode:'Av ou M', aperture:'f/3.5–4.5', shutter:'1/60 s mínimo', iso:'800–3200', focus:'One Shot', tip:'Encoste o corpo numa parede, prenda a respiração e fotografe em sequência. Se tiver apoio firme, use temporizador de 2 s.', steps:['Abra a lente: use o menor número f disponível.','Suba o ISO para 1600.','Ative o estabilizador da lente (IS).','Se borrar, use 18 mm e procure mais luz.'], avoid:'Evite zoom de 55 mm à noite: a lente fica mais escura e treme mais.' },
  { id:'perto', icon:Focus, title:'De perto', label:'Perto', color:'leaf', lens:'55 mm', mode:'Av', aperture:'f/5.6–8', shutter:'1/125 s ou mais', iso:'Auto até 1600', focus:'One Shot', tip:'Afaste-se cerca de 25 cm ou mais do objeto. Use 55 mm para fundo mais suave e toque na tela onde quer nitidez.', steps:['Coloque a chave da lente em AF.','Gire o zoom até 55 mm.','Use f/5.6 e aproxime devagar.','Se não focar, afaste a câmera alguns centímetros.'], avoid:'A 18–55 mm não é macro: perto demais ela simplesmente não consegue focar.' },
  { id:'longe', icon:Mountain, title:'De longe', label:'Longe', color:'sky', lens:'55 mm', mode:'Tv', aperture:'Automática', shutter:'1/500 s', iso:'Auto', focus:'AI Servo', tip:'Use 55 mm, mas procure incluir o ambiente na composição. Esta lente não transforma assuntos muito distantes em close.', steps:['Gire o seletor para Tv.','Defina 1/500 s.','Selecione AI Servo para algo em movimento.','Acompanhe o assunto suavemente antes de disparar.'], avoid:'Zoom digital depois da foto reduz a qualidade; chegue mais perto apenas quando for seguro.' },
  { id:'lua', icon:Sparkles, title:'A Lua', label:'Lua', color:'moon', lens:'55 mm', mode:'M', aperture:'f/8', shutter:'1/125–1/250 s', iso:'100–400', focus:'Manual / Live View', tip:'A Lua é muito clara. Ela ficará pequena com 55 mm — componha com árvores, prédios ou paisagem e recorte só um pouco depois.', steps:['Apoie a câmera e desligue o IS se usar tripé.','Use M: f/8, 1/200 s, ISO 200.','Amplie a imagem no Live View e foque manualmente.','Use temporizador de 2 s e ajuste se ficar clara demais.'], avoid:'Modo automático costuma transformar a Lua numa bola branca sem detalhes.' },
  { id:'safari', icon:PawPrint, title:'Bichos no safari', label:'Safari', color:'safari', lens:'55 mm', mode:'Tv', aperture:'Automática', shutter:'1/1000 s', iso:'Auto (máx. 3200)', focus:'AI Servo + contínuo', tip:'Antecipe o movimento e deixe espaço para onde o animal está olhando. Inclua a paisagem: com 55 mm, fotos ambientais ficam melhores.', steps:['Fique no veículo e siga sempre o guia.','Use 55 mm e 1/1000 s.','Ative disparo contínuo e AI Servo.','Mantenha o ponto de foco sobre o olho ou cabeça.'], avoid:'Nunca se aproxime, alimente ou use flash nos animais.' },
];
const basics = [{icon:Aperture,name:'Abertura (f/)',text:'Número menor = entra mais luz e o fundo fica mais suave.'},{icon:Zap,name:'Velocidade',text:'Número mais rápido congela ação; lento pode borrar.'},{icon:Gauge,name:'ISO',text:'Aumenta a claridade, mas também o granulado.'}];

export default function Home(){
  const [active,setActive]=useState('dia'); const [menu,setMenu]=useState(false); const [expanded,setExpanded]=useState<string|null>('dia'); const [online,setOnline]=useState(true); const [offlineReady,setOfflineReady]=useState(false); const selected=scenarios.find(s=>s.id===active)!;
  useEffect(()=>{
    setOnline(navigator.onLine); const onOnline=()=>setOnline(true); const onOffline=()=>setOnline(false); window.addEventListener('online',onOnline); window.addEventListener('offline',onOffline);
    if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js').then(()=>navigator.serviceWorker.ready).then(reg=>{const urls=[location.href,...performance.getEntriesByType('resource').map(entry=>(entry as PerformanceResourceTiming).name)].filter(url=>url.startsWith(location.origin));const channel=new MessageChannel();channel.port1.onmessage=()=>setOfflineReady(true);reg.active?.postMessage({type:'CACHE_URLS',urls},[channel.port2])}).catch(()=>setOfflineReady(false))}
    return()=>{window.removeEventListener('online',onOnline);window.removeEventListener('offline',onOffline)};
  },[]);
  const jump=(id:string)=>{setActive(id);setExpanded(id);setMenu(false);document.getElementById('guia')?.scrollIntoView({behavior:'smooth'})};
  return <main><header className="topbar"><a className="brand" href="#inicio"><span className="brandmark"><Camera size={21}/></span><span>SL2 <b>de bolso</b></span></a><button className="menuButton" onClick={()=>setMenu(!menu)} aria-label="Abrir menu">{menu?<X/>:<Menu/>}</button><nav className={menu?'nav open':'nav'}><a href="#primeiros">Comece aqui</a><a href="#guia">Situações</a><a href="#controles">Controles</a><a href="#offline"><Download size={15}/> Offline</a></nav></header>
  <section id="inicio" className="hero"><div className="heroCopy"><span className="eyebrow">Manual visual para iniciantes</span><h1>Sua Canon SL2.<br/><em>Sem complicação.</em></h1><p>Configurações práticas para fotografar com a lente 18–55 mm — de um dia ensolarado à Lua, passando por noites e safáris.</p><div className="heroActions"><button onClick={()=>jump('dia')} className="primary">Escolher uma situação</button><a href="#primeiros" className="textLink">Entender o básico <span>↓</span></a></div><div className="heroNote"><span>100% offline</span><span>•</span><span>feito para iPhone</span></div></div><div className="heroVisual"><img src="images/camera-hero.webp" width="1200" height="900" fetchPriority="high" alt="Fotografia da Canon EOS Rebel SL2 com lente 18–55 mm"/><div className="lensBadge"><small>SUA ÚNICA LENTE</small><b>18—55</b><span>mm</span></div></div></section>
  <section id="primeiros" className="intro section"><div className="sectionHeading"><span className="kicker">01 · Antes de começar</span><h2>Três ideias. Só isso.</h2><p>Uma foto é o equilíbrio entre luz, movimento e granulação.</p></div><div className="basics">{basics.map((b,i)=><article key={b.name} className="basicCard"><span className="step">0{i+1}</span><b.icon/><h3>{b.name}</h3><p>{b.text}</p></article>)}</div><div className="goldenRule"><Sparkles/><div><b>A regra de ouro</b><span>Se a foto borrar, aumente a velocidade. Se ficar escura, aumente o ISO.</span></div></div></section>
  <section id="guia" className="guide section"><div className="sectionHeading light"><span className="kicker">02 · Guia por situação</span><h2>O que você quer fotografar?</h2><p>Toque numa situação e copie a receita. Depois ajuste um item por vez.</p></div><div className="scenarioTabs">{scenarios.map(s=><button key={s.id} onClick={()=>{setActive(s.id);setExpanded(s.id)}} className={active===s.id?'active':''}><s.icon/>{s.label}</button>)}</div><div className={`recipe ${selected.color}`}><div className="recipeTop"><div><span className="recipeLabel">Receita rápida</span><h3>{selected.title}</h3></div><selected.icon className="recipeIcon"/></div><div className="settings"><div><small>LENTE</small><b>{selected.lens}</b></div><div><small>MODO</small><b>{selected.mode}</b></div><div><small>ABERTURA</small><b>{selected.aperture}</b></div><div><small>VELOCIDADE</small><b>{selected.shutter}</b></div><div><small>ISO</small><b>{selected.iso}</b></div><div><small>FOCO</small><b>{selected.focus}</b></div></div><div className="tip"><span>💡</span><p><b>Dica que faz diferença</b>{selected.tip}</p></div><button className="stepsToggle" onClick={()=>setExpanded(expanded===selected.id?null:selected.id)}>Passo a passo <ChevronDown className={expanded===selected.id?'rotated':''}/></button>{expanded===selected.id&&<div className="steps"><ol>{selected.steps.map(step=><li key={step}>{step}</li>)}</ol><div className="avoid"><b>Evite</b><span>{selected.avoid}</span></div></div>}</div></section>
  <section className="gallery section"><div className="sectionHeading"><span className="kicker">03 · Veja a intenção</span><h2>A lente muda a história.</h2></div><div className="imageGrid"><figure><img src="images/dia-noite.webp" width="1400" height="900" loading="lazy" decoding="async" alt="Comparação visual entre paisagem de dia e rua à noite"/><figcaption><b>Dia × noite</b><span>De dia, feche a abertura. À noite, procure luz e firme a câmera.</span></figcaption></figure><figure><img src="images/lua-safari.webp" width="1400" height="900" loading="lazy" decoding="async" alt="Comparação visual entre fotografia da Lua e animais em safari"/><figcaption><b>Lua × safari</b><span>A Lua pede controle manual. Animais pedem velocidade e antecipação.</span></figcaption></figure></div></section>
  <section id="controles" className="controls section"><div className="sectionHeading light"><span className="kicker">04 · Conheça sua câmera</span><h2>Onde mexer primeiro.</h2><p>Estas são fotos da sua própria SL2. Use-as como mapa quando estiver com a câmera na mão.</p></div><div className="cameraPhotos"><figure><img src="images/sl2-seletor.webp" loading="lazy" decoding="async" alt="Parte superior da Canon SL2 mostrando seletor de modos, ISO e botão de ligar"/><figcaption><span>①</span><div><b>Seletor e ISO</b><p>Gire para <strong>Av</strong>, <strong>Tv</strong> ou <strong>M</strong>. O botão <strong>ISO</strong> fica logo acima.</p></div></figcaption></figure><figure><img src="images/sl2-lente.webp" loading="lazy" decoding="async" alt="Lente Canon 18–55 mm mostrando zoom, foco AF MF e estabilizador"/><figcaption><span>②</span><div><b>Zoom, foco e estabilizador</b><p>Gire entre <strong>18 e 55 mm</strong>. Para começar, deixe <strong>AF</strong> e <strong>STABILIZER ON</strong>.</p></div></figcaption></figure><figure><img src="images/sl2-traseira.webp" loading="lazy" decoding="async" alt="Parte traseira da Canon SL2 mostrando botões Q Set e compensação de exposição"/><figcaption><span>③</span><div><b>Q/SET e compensação</b><p><strong>Q</strong> abre os ajustes rápidos. O botão <strong>Av ±</strong> ajuda a clarear ou escurecer.</p></div></figcaption></figure><figure><img src="images/sl2-visao-superior.webp" loading="lazy" decoding="async" alt="Vista superior da Canon SL2 mostrando os principais controles"/><figcaption><span>④</span><div><b>Roda de ajuste</b><p>Gire a pequena roda perto do disparador para mudar abertura, velocidade ou outro valor selecionado.</p></div></figcaption></figure></div><div className="controlGrid"><article><span>⑤</span><div><b>Meio disparador</b><p>Aperte o disparador até a metade, espere o foco confirmar e só então fotografe.</p></div></article><article><span>⑥</span><div><b>Botão com asterisco</b><p>O botão <strong>✱</strong> trava a exposição. No começo, pode deixá-lo para depois.</p></div></article></div></section>
  <section id="offline" className="offline section"><div><span className="kicker">Leve para qualquer lugar</span><h2>Funciona sem internet.</h2><p>No Safari do iPhone, toque em <b>Compartilhar</b> e depois em <b>Adicionar à Tela de Início</b>. Aguarde a confirmação abaixo antes de sair de casa.</p><div className={`pwaStatus ${offlineReady?'ready':''}`}>{offlineReady?<CheckCircle2/>:<Download/>}<div><b>{offlineReady?'Pronto para usar offline':'Preparando o modo offline…'}</b><span>{online?'Você está conectado à internet.':'Você está sem internet agora.'}</span></div></div></div><div className="phoneSteps"><span>1</span><p>Abra no Safari</p><i>↓</i><span>2</span><p>Toque em Compartilhar</p><i>↓</i><span>3</span><p>Adicionar à Tela de Início</p><i>↓</i><span>4</span><p>Abra pelo novo ícone</p></div></section><footer><div className="brand"><span className="brandmark"><Camera size={20}/></span><span>SL2 <b>de bolso</b></span></div><p>Guia independente para Canon EOS Rebel SL2 + lente 18–55 mm.</p><a href="#inicio">Voltar ao topo ↑</a></footer><nav className="mobileDock" aria-label="Navegação rápida"><a href="#inicio"><HomeIcon/><span>Início</span></a><a href="#guia"><Camera/><span>Fotos</span></a><a href="#controles"><Aperture/><span>Câmera</span></a><a href="#offline" className={offlineReady?'isReady':''}>{online?<Download/>:<WifiOff/>}<span>Offline</span></a></nav></main>
}
