'use client';

import { useEffect, useState } from 'react';
import { Aperture, Camera, CheckCircle2, ChevronDown, Download, Focus, Gauge, Home as HomeIcon, Menu, Moon, Mountain, PawPrint, Sparkles, Sun, WifiOff, X, Zap } from 'lucide-react';

const scenarios = [
  { id:'dia', icon:Sun, title:'Fotos de dia', label:'Dia', color:'sun', lens:'18–35 mm', mode:'Av', aperture:'f/8', shutter:'1/250 s ou mais', iso:'100–200', focus:'One Shot', tip:'Comece com o sol de lado ou atrás de você. Para paisagens, use 18 mm; para pessoas, aproxime para 35–55 mm.', steps:['Gire o seletor para Av.','Escolha f/8 e ISO 100.','Aperte o disparador até a metade para focar.','Confira se a velocidade ficou em 1/125 s ou mais.'], avoid:'Sol forte direto no rosto cria olhos semicerrados e sombras duras.' },
  { id:'noite', icon:Moon, title:'Fotos à noite', label:'Noite', color:'night', lens:'18–35 mm', mode:'Av ou M', aperture:'f/3.5–4.5', shutter:'1/60 s mínimo', iso:'800–3200', focus:'One Shot', tip:'Encoste o corpo numa parede, prenda a respiração e fotografe em sequência. Se tiver apoio firme, use temporizador de 2 s.', steps:['Abra a lente: use o menor número f disponível.','Suba o ISO para 1600.','Ative o estabilizador da lente (IS).','Se borrar, use 18 mm e procure mais luz.'], avoid:'Evite zoom de 55 mm à noite: a lente fica mais escura e treme mais.' },
  { id:'perto', icon:Focus, title:'De perto', label:'Perto', color:'leaf', lens:'55 mm', mode:'Av', aperture:'f/5.6–8', shutter:'1/125 s ou mais', iso:'Auto até 1600', focus:'One Shot', tip:'Afaste-se cerca de 25 cm ou mais do objeto. Use 55 mm para fundo mais suave e toque na tela onde quer nitidez.', steps:['Coloque a chave da lente em AF.','Gire o zoom até 55 mm.','Use f/5.6 e aproxime devagar.','Se não focar, afaste a câmera alguns centímetros.'], avoid:'A 18–55 mm não é macro: perto demais ela simplesmente não consegue focar.' },
  { id:'longe', icon:Mountain, title:'De longe', label:'Longe', color:'sky', lens:'55 mm', mode:'Tv', aperture:'Automática', shutter:'1/500 s', iso:'Auto', focus:'AI Servo', tip:'Use 55 mm, mas procure incluir o ambiente na composição. Esta lente não transforma assuntos muito distantes em close.', steps:['Gire o seletor para Tv.','Defina 1/500 s.','Selecione AI Servo para algo em movimento.','Acompanhe o assunto suavemente antes de disparar.'], avoid:'Zoom digital depois da foto reduz a qualidade; chegue mais perto apenas quando for seguro.' },
  { id:'lua', icon:Sparkles, title:'A Lua', label:'Lua', color:'moon', lens:'55 mm', mode:'M', aperture:'f/8', shutter:'1/125–1/250 s', iso:'100–400', focus:'Manual / Live View', tip:'A Lua é muito clara. Ela ficará pequena com 55 mm — componha com árvores, prédios ou paisagem e recorte só um pouco depois.', steps:['Apoie a câmera e desligue o IS se usar tripé.','Use M: f/8, 1/200 s, ISO 200.','Amplie a imagem no Live View e foque manualmente.','Use temporizador de 2 s e ajuste se ficar clara demais.'], avoid:'Modo automático costuma transformar a Lua numa bola branca sem detalhes.' },
  { id:'safari', icon:PawPrint, title:'Bichos no safari', label:'Safari', color:'safari', lens:'55 mm', mode:'Tv', aperture:'Automática', shutter:'1/1000 s', iso:'Auto (máx. 3200)', focus:'AI Servo + contínuo', tip:'Antecipe o movimento e deixe espaço para onde o animal está olhando. Inclua a paisagem: com 55 mm, fotos ambientais ficam melhores.', steps:['Fique no veículo e siga sempre o guia.','Use 55 mm e 1/1000 s.','Ative disparo contínuo e AI Servo.','Mantenha o ponto de foco sobre o olho ou cabeça.'], avoid:'Nunca se aproxime, alimente ou use flash nos animais.' },
];
const basics = [{icon:Aperture,name:'Abertura (f/)',text:'Número menor = entra mais luz e o fundo fica mais suave.'},{icon:Zap,name:'Velocidade',text:'Número mais rápido congela ação; lento pode borrar.'},{icon:Gauge,name:'ISO',text:'Aumenta a claridade, mas também o granulado.'}];
const preparation = [
  ['Bateria e cartão','Carregue a bateria, coloque o cartão e confira se há espaço antes de sair.'],
  ['Qualidade da foto','MENU → Qualidade da imagem → escolha L para JPEG grande. Use RAW+L quando quiser editar depois.'],
  ['Lente pronta','Encaixe a lente até ouvir o clique. Deixe AF e STABILIZER em ON para fotografar na mão.'],
  ['Visor ajustado','Olhe pelo visor e gire a pequena dioptria ao lado dele até os números aparecerem nítidos.'],
  ['Ponto de foco','Comece com um único ponto central. Coloque-o sobre o olho, rosto ou detalhe importante.'],
  ['Segure firme','Mão direita no corpo, esquerda sustentando a lente e cotovelos próximos ao peito.'],
];
const problems = [
  ['A foto ficou escura','Aumente o ISO, use uma abertura menor em número ou procure mais luz. Em Av, use compensação +1.'],
  ['A foto ficou clara demais','Baixe o ISO. Em Av, use compensação −1. Para a Lua, aumente a velocidade.'],
  ['A foto ficou tremida','Aumente a velocidade, use 18 mm, apoie a câmera e confirme STABILIZER ON.'],
  ['O assunto ficou borrado','Troque para AI Servo e use 1/500 s; para animais correndo, comece em 1/1000 s.'],
  ['A câmera não consegue focar','Procure contraste, use o ponto central, afaste-se um pouco e confirme que a lente está em AF.'],
  ['A imagem tem muito granulado','Reduza o ISO e aceite uma velocidade menor somente se a câmera e o assunto estiverem parados.'],
];
const officialGroups = [
  {tag:'Controle rápido',title:'Ajustes sem se perder no menu',intro:'Os atalhos que valem aprender primeiro.',items:[
    ['Tela Q — seu painel principal','Pressione Q, toque no ajuste desejado e gire a roda. Por ali você muda foco, disparo, medição, qualidade, balanço de branco e estilo de imagem sem procurar nas abas do MENU.'],
    ['Um ponto de foco, mais precisão','Pressione o botão de seleção de ponto AF e escolha o ponto central. Aponte-o para o olho ou detalhe principal, pressione o disparador pela metade e recomponha mantendo-o pressionado.'],
    ['One Shot × AI Servo','Use One Shot para paisagem, objetos e pessoas paradas. Use AI Servo para animais, crianças e veículos: mantenha o ponto no assunto enquanto a câmera corrige o foco continuamente.'],
    ['Live View e foco pelo toque','Pressione o botão Live View, toque no rosto ou detalhe e fotografe. Ative o obturador por toque no ícone inferior da tela para focar e disparar com um único toque.'],
  ]},
  {tag:'Luz e cor',title:'Fotos prontas mais bonitas',intro:'Recursos internos que melhoram o JPEG sem edição.',items:[
    ['Compensação de exposição','Em Av ou Tv, segure o botão Av ± e gire a roda: use +1 quando o rosto estiver escuro; use −1 quando áreas claras estiverem estourando. Depois volte o marcador para zero.'],
    ['Medição avaliativa','Deixe em Avaliativa para quase tudo, inclusive contraluz. Para medir uma parte pequena e importante, use Parcial; deixe Pontual para quando já estiver mais confortável.'],
    ['Trava de exposição ✱','Meça a luz no rosto, aperte ✱ e depois recomponha. O asterisco no visor confirma a trava — muito útil quando a pessoa está diante de uma janela ou pôr do sol.'],
    ['Balanço de branco','Auto funciona na maioria das vezes. Se a foto ficar laranja em luz de casa, escolha Tungstênio; em sombra muito azul, escolha Sombra. Volte para Auto ao mudar de lugar.'],
    ['Estilo de imagem','Standard é seguro. Portrait suaviza pele; Landscape reforça azul e verde; Neutral é discreto e melhor para editar. O estilo afeta o JPEG, não elimina os dados do RAW.'],
    ['Correção da lente','Em MENU → correção de aberração da lente, mantenha iluminação periférica, aberração cromática e difração ativadas. Elas ajudam a corrigir cantos escuros e franjas de cor da 18–55 mm.'],
  ]},
  {tag:'Disparo inteligente',title:'Recursos que aumentam seus acertos',intro:'Úteis para movimento, pouca luz e fotos em grupo.',items:[
    ['Contínuo de até 5 fotos/s','Pressione Q → modo de avanço → Contínuo. Mantenha o disparador pressionado para ação, animais e expressões. Faça sequências curtas para não lotar o cartão.'],
    ['Disparo silencioso','Escolha Silencioso simples quando quiser menos ruído em cerimônias ou animais calmos. O contínuo silencioso é mais lento, chegando a aproximadamente 2,5 fotos/s.'],
    ['Temporizador de 2 segundos','Ideal com tripé, apoio ou fotografia da Lua: ele evita o tremor causado ao tocar no disparador. O temporizador de 10 segundos serve para entrar na foto.'],
    ['Redução de ruído em ISO alto','MENU → Redução de ruído de ISO alto. Comece em Standard. A opção Multi Shot combina quatro fotos, mas pede câmera firme e assunto parado.'],
    ['Redução em longa exposição','Para exposições de 1 segundo ou mais, ative a redução de ruído de longa exposição. A câmera pode levar um tempo semelhante ao da foto para processar.'],
    ['Lembrete sem cartão','MENU → Disparar obturador sem cartão → Desativar. Assim a câmera impede uma “foto” que não seria gravada — ótimo antes de viagens e safáris.'],
  ]},
  {tag:'Vídeo e celular',title:'Funções escondidas e divertidas',intro:'A SL2 também grava, automatiza e conversa com o iPhone.',items:[
    ['Vídeo Full HD','Coloque a chave em vídeo e escolha 1920×1080. Para uso comum, 29,97/25 fps é natural; 59,94/50 fps ajuda em movimento e câmera lenta na edição. Use cartão Classe 10.'],
    ['Som melhor','A câmera grava estéreo e aceita microfone externo na entrada dedicada. Antes de uma gravação importante, faça um teste curto e confira se o medidor de áudio reage sem bater no máximo.'],
    ['Time-lapse automático','No menu de vídeo, ative Filme time-lapse, defina intervalo e número de fotos e deixe a câmera firme. Funciona muito bem com nuvens, pôr do sol e movimento de pessoas.'],
    ['Canon Camera Connect','Ative Wi‑Fi na câmera e use o aplicativo Canon Camera Connect no iPhone para ver e transferir fotos, além de controlar a câmera remotamente — útil em tripé e fotos de grupo.'],
    ['Localização pelo iPhone','Com um smartphone Bluetooth compatível conectado, a câmera pode anexar dados de localização às imagens. Ative somente quando precisar para economizar bateria.'],
    ['Revisão que ajuda de verdade','Ajuste a revisão para 4 segundos e mantenha o brilho da tela no nível central ao avaliar exposição. Amplie o olho ou detalhe principal para conferir foco, não apenas a imagem inteira.'],
  ]},
];

export default function Home(){
  const [active,setActive]=useState('dia'); const [menu,setMenu]=useState(false); const [expanded,setExpanded]=useState<string|null>('dia'); const [online,setOnline]=useState(true); const [offlineReady,setOfflineReady]=useState(false); const selected=scenarios.find(s=>s.id===active)!;
  useEffect(()=>{
    setOnline(navigator.onLine); const onOnline=()=>setOnline(true); const onOffline=()=>setOnline(false); window.addEventListener('online',onOnline); window.addEventListener('offline',onOffline);
    if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js').then(()=>navigator.serviceWorker.ready).then(reg=>{const urls=[location.href,...performance.getEntriesByType('resource').map(entry=>(entry as PerformanceResourceTiming).name)].filter(url=>url.startsWith(location.origin));const channel=new MessageChannel();channel.port1.onmessage=()=>setOfflineReady(true);reg.active?.postMessage({type:'CACHE_URLS',urls},[channel.port2])}).catch(()=>setOfflineReady(false))}
    return()=>{window.removeEventListener('online',onOnline);window.removeEventListener('offline',onOffline)};
  },[]);
  const jump=(id:string)=>{setActive(id);setExpanded(id);setMenu(false);document.getElementById('guia')?.scrollIntoView({behavior:'smooth'})};
  return <main><header className="topbar"><a className="brand" href="#inicio"><span className="brandmark"><Camera size={21}/></span><span>SL2 <b>de bolso</b></span></a><button className="menuButton" onClick={()=>setMenu(!menu)} aria-label="Abrir menu">{menu?<X/>:<Menu/>}</button><nav className={menu?'nav open':'nav'}><a href="#primeiros">Comece aqui</a><a href="#guia">Situações</a><a href="#controles">Controles</a><a href="#recursos">Recursos</a><a href="#offline"><Download size={15}/> Offline</a></nav></header>
  <section id="inicio" className="hero"><div className="heroCopy"><span className="eyebrow">Manual visual para iniciantes</span><h1>Sua Canon SL2.<br/><em>Sem complicação.</em></h1><p>Configurações práticas para fotografar com a lente 18–55 mm — de um dia ensolarado à Lua, passando por noites e safáris.</p><div className="heroActions"><button onClick={()=>jump('dia')} className="primary">Escolher uma situação</button><a href="#primeiros" className="textLink">Entender o básico <span>↓</span></a></div><div className="heroNote"><span>100% offline</span><span>•</span><span>feito para iPhone</span></div></div><div className="heroVisual"><img src="images/camera-hero.webp" width="1200" height="900" fetchPriority="high" alt="Fotografia da Canon EOS Rebel SL2 com lente 18–55 mm"/><div className="lensBadge"><small>SUA ÚNICA LENTE</small><b>18—55</b><span>mm</span></div></div></section>
  <section id="primeiros" className="intro section"><div className="sectionHeading"><span className="kicker">01 · Antes de começar</span><h2>Três ideias. Só isso.</h2><p>Uma foto é o equilíbrio entre luz, movimento e granulação.</p></div><div className="basics">{basics.map((b,i)=><article key={b.name} className="basicCard"><span className="step">0{i+1}</span><b.icon/><h3>{b.name}</h3><p>{b.text}</p></article>)}</div><div className="goldenRule"><Sparkles/><div><b>A regra de ouro</b><span>Se a foto borrar, aumente a velocidade. Se ficar escura, aumente o ISO.</span></div></div></section>
  <section className="prepare section"><div className="sectionHeading"><span className="kicker">Antes da primeira foto</span><h2>Deixe a câmera pronta.</h2><p>Faça esta preparação uma vez com calma. Depois, no passeio, você só escolhe a situação e fotografa.</p></div><figure className="widePhoto"><img src="images/preparacao-camera.webp" loading="lazy" decoding="async" alt="Canon SL2 com lente, bateria, cartão, alça e pano de limpeza organizados sobre uma mesa clara"/><figcaption><b>Antes de sair</b><span>Câmera, bateria carregada, cartão com espaço, alça segura e lente limpa.</span></figcaption></figure><div className="prepareGrid">{preparation.map(([title,text],i)=><article key={title}><span>{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div><div className="lensMap"><div><small>18 mm</small><b>Mais ambiente</b><p>Paisagem, interiores, grupo de pessoas e fotos noturnas na mão.</p></div><i>gire o zoom →</i><div><small>35 mm</small><b>Visão natural</b><p>Passeios, pessoas no ambiente e cenas do cotidiano.</p></div><i>gire o zoom →</i><div><small>55 mm</small><b>Mais aproximação</b><p>Retrato, detalhes, animais próximos e Lua dentro da paisagem.</p></div></div><div className="modeGuide"><b>Qual modo escolher?</b><span><strong>Av</strong> para controlar fundo e luz</span><span><strong>Tv</strong> para controlar movimento</span><span><strong>M</strong> para Lua e situações previsíveis</span></div></section>
  <section id="guia" className="guide section"><div className="sectionHeading light"><span className="kicker">02 · Guia por situação</span><h2>O que você quer fotografar?</h2><p>Toque numa situação e copie a receita. Depois ajuste um item por vez.</p></div><div className="scenarioTabs">{scenarios.map(s=><button key={s.id} onClick={()=>{setActive(s.id);setExpanded(s.id)}} className={active===s.id?'active':''}><s.icon/>{s.label}</button>)}</div><div className={`recipe ${selected.color}`}><div className="recipeTop"><div><span className="recipeLabel">Receita rápida</span><h3>{selected.title}</h3></div><selected.icon className="recipeIcon"/></div><div className="settings"><div><small>LENTE</small><b>{selected.lens}</b></div><div><small>MODO</small><b>{selected.mode}</b></div><div><small>ABERTURA</small><b>{selected.aperture}</b></div><div><small>VELOCIDADE</small><b>{selected.shutter}</b></div><div><small>ISO</small><b>{selected.iso}</b></div><div><small>FOCO</small><b>{selected.focus}</b></div></div><div className="tip"><span>💡</span><p><b>Dica que faz diferença</b>{selected.tip}</p></div><button className="stepsToggle" onClick={()=>setExpanded(expanded===selected.id?null:selected.id)}>Passo a passo <ChevronDown className={expanded===selected.id?'rotated':''}/></button>{expanded===selected.id&&<div className="steps"><ol>{selected.steps.map(step=><li key={step}>{step}</li>)}</ol><div className="avoid"><b>Evite</b><span>{selected.avoid}</span></div></div>}</div><figure className="widePhoto darkPhoto"><img src="images/foco-safari.webp" loading="lazy" decoding="async" alt="Zebra caminhando no safari com olho nítido e espaço à frente do movimento"/><figcaption><b>Foco que acompanha</b><span>AI Servo + 1/1000 s + espaço na direção do movimento. Com 55 mm, inclua o ambiente.</span></figcaption></figure></section>
  <section className="gallery section"><div className="sectionHeading"><span className="kicker">03 · Veja a intenção</span><h2>A lente muda a história.</h2></div><div className="imageGrid"><figure><img src="images/dia-noite.webp" width="1400" height="900" loading="lazy" decoding="async" alt="Comparação visual entre paisagem de dia e rua à noite"/><figcaption><b>Dia × noite</b><span>De dia, feche a abertura. À noite, procure luz e firme a câmera.</span></figcaption></figure><figure><img src="images/lua-safari.webp" width="1400" height="900" loading="lazy" decoding="async" alt="Comparação visual entre fotografia da Lua e animais em safari"/><figcaption><b>Lua × safari</b><span>A Lua pede controle manual. Animais pedem velocidade e antecipação.</span></figcaption></figure></div></section>
  <section id="controles" className="controls section"><div className="sectionHeading light"><span className="kicker">04 · Conheça sua câmera</span><h2>Onde mexer primeiro.</h2><p>Estas são fotos da sua própria SL2. Use-as como mapa quando estiver com a câmera na mão.</p></div><div className="cameraPhotos"><figure><img src="images/sl2-seletor.webp" loading="lazy" decoding="async" alt="Parte superior da Canon SL2 mostrando seletor de modos, ISO e botão de ligar"/><figcaption><span>①</span><div><b>Seletor e ISO</b><p>Gire para <strong>Av</strong>, <strong>Tv</strong> ou <strong>M</strong>. O botão <strong>ISO</strong> fica logo acima.</p></div></figcaption></figure><figure><img src="images/sl2-lente.webp" loading="lazy" decoding="async" alt="Lente Canon 18–55 mm mostrando zoom, foco AF MF e estabilizador"/><figcaption><span>②</span><div><b>Zoom, foco e estabilizador</b><p>Gire entre <strong>18 e 55 mm</strong>. Para começar, deixe <strong>AF</strong> e <strong>STABILIZER ON</strong>.</p></div></figcaption></figure><figure><img src="images/sl2-traseira.webp" loading="lazy" decoding="async" alt="Parte traseira da Canon SL2 mostrando botões Q Set e compensação de exposição"/><figcaption><span>③</span><div><b>Q/SET e compensação</b><p><strong>Q</strong> abre os ajustes rápidos. O botão <strong>Av ±</strong> ajuda a clarear ou escurecer.</p></div></figcaption></figure><figure><img src="images/sl2-visao-superior.webp" loading="lazy" decoding="async" alt="Vista superior da Canon SL2 mostrando os principais controles"/><figcaption><span>④</span><div><b>Roda de ajuste</b><p>Gire a pequena roda perto do disparador para mudar abertura, velocidade ou outro valor selecionado.</p></div></figcaption></figure></div><div className="controlGrid"><article><span>⑤</span><div><b>Meio disparador</b><p>Aperte o disparador até a metade, espere o foco confirmar e só então fotografe.</p></div></article><article><span>⑥</span><div><b>Botão com asterisco</b><p>O botão <strong>✱</strong> trava a exposição. No começo, pode deixá-lo para depois.</p></div></article></div></section>
  <section className="solve section"><div className="sectionHeading"><span className="kicker">05 · Se algo der errado</span><h2>Conserte a foto na hora.</h2><p>Veja o sintoma na tela, altere apenas um ajuste e tente novamente.</p></div><figure className="widePhoto exposurePhoto"><img src="images/exposicao-retrato.webp" loading="lazy" decoding="async" alt="Mesmo retrato escuro, corretamente exposto e claro demais em três comparações"/><figcaption><b>Escura · correta · clara demais</b><span>No modo Av ou Tv, use a compensação ± para levar a foto em direção ao resultado central.</span></figcaption></figure><div className="problemGrid">{problems.map(([title,text])=><details key={title}><summary>{title}<ChevronDown/></summary><p>{text}</p></details>)}</div><div className="fieldChecklist"><div><b>Checklist de 10 segundos</b><p>Modo certo · ISO adequado · foco confirmado · velocidade segura · cartão e bateria</p></div><div><b>Revise ampliando</b><p>Depois da foto, aperte ▶ e amplie o olho ou detalhe principal. A tela pequena pode esconder tremido.</p></div><div><b>Faça uma sequência</b><p>Em animais, pessoas e pouca luz, faça 3 fotos. Pequenas diferenças aumentam a chance de nitidez.</p></div></div></section>
  <section id="recursos" className="features section"><div className="sectionHeading"><span className="kicker">06 · Recursos do manual oficial</span><h2>Mais poder, sem complicação.</h2><p>Funções selecionadas do manual da Canon e traduzidas em usos simples para o dia a dia.</p></div><div className="featurePhotos"><figure><img src="images/postura-noturna.webp" loading="lazy" decoding="async" alt="Fotógrafa segurando a Canon corretamente em uma rua iluminada à noite"/><figcaption><b>Mais firmeza à noite</b><span>Mão esquerda sob a lente, cotovelos junto ao corpo e disparo suave.</span></figcaption></figure><figure><img src="images/camera-iphone-remoto.webp" loading="lazy" decoding="async" alt="Canon em tripé controlada remotamente por um iPhone durante o pôr do sol"/><figcaption><b>Controle pelo iPhone</b><span>Tripé + Camera Connect para grupo, paisagem, longa exposição e time-lapse.</span></figcaption></figure></div><div className="featureGroups">{officialGroups.map(group=><article className="featureGroup" key={group.tag}><header><span>{group.tag}</span><h3>{group.title}</h3><p>{group.intro}</p></header><div>{group.items.map(([title,text],i)=><details key={title}><summary><b>{String(i+1).padStart(2,'0')}</b><span>{title}</span><ChevronDown/></summary><p>{text}</p></details>)}</div></article>)}</div><aside className="sourceNote"><CheckCircle2/><div><b>Baseado na documentação oficial</b><span>Conteúdo adaptado do Instruction Manual Canon EOS Rebel SL2 / EOS 200D. Os nomes podem aparecer em inglês ou português conforme o idioma configurado na câmera.</span></div></aside></section>
  <section id="offline" className="offline section"><div><span className="kicker">Leve para qualquer lugar</span><h2>Funciona sem internet.</h2><p>No Safari do iPhone, toque em <b>Compartilhar</b> e depois em <b>Adicionar à Tela de Início</b>. Aguarde a confirmação abaixo antes de sair de casa.</p><div className={`pwaStatus ${offlineReady?'ready':''}`}>{offlineReady?<CheckCircle2/>:<Download/>}<div><b>{offlineReady?'Pronto para usar offline':'Preparando o modo offline…'}</b><span>{online?'Você está conectado à internet.':'Você está sem internet agora.'}</span></div></div></div><div className="phoneSteps"><span>1</span><p>Abra no Safari</p><i>↓</i><span>2</span><p>Toque em Compartilhar</p><i>↓</i><span>3</span><p>Adicionar à Tela de Início</p><i>↓</i><span>4</span><p>Abra pelo novo ícone</p></div></section><footer><div className="brand"><span className="brandmark"><Camera size={20}/></span><span>SL2 <b>de bolso</b></span></div><p>Guia independente para Canon EOS Rebel SL2 + lente 18–55 mm.</p><a href="#inicio">Voltar ao topo ↑</a></footer><nav className="mobileDock" aria-label="Navegação rápida"><a href="#inicio"><HomeIcon/><span>Início</span></a><a href="#guia"><Camera/><span>Fotos</span></a><a href="#recursos"><Sparkles/><span>Recursos</span></a><a href="#offline" className={offlineReady?'isReady':''}>{online?<Download/>:<WifiOff/>}<span>Offline</span></a></nav></main>
}
